### PR TITLE
Support for horizon demandsupply level bar, added json files to gitignore, removed mrmptestlab, Product directory now also checks for elite-

### PR DESCRIPTION
**Pull request by MRmP**
Note: Not backwards compatible with old Low/Med/High demandsupply level
Calibration points and examples need to be updated with the new level
bar

### CODE REVIEW

**Comment by MRmP** [comment]
I agree :) The following edit was just to be able to run RN on my own system before I got to set up the SQL version

**Comment by Duke-Jones** [comment]
Ok, what do you want to do next ?

I have to actual things in the pipe:
- adding unknown commodities to the database after scanning or getting the from the EDMC
- changing all remaining references from the old settings file to the database and create a import function to  import these settings from the old file

important "to do" before first beta release:
- creating a installer which automatically creates the whole structure
- consider the new structures from EDDN for importing actual data (see api-changes on https://eddb.io/api for v4)
- 

planned next things
- more clean up (putting chaos from Form1 into own files as done by CommandersLog/Settings/PriceRouteCalculation)
- reactivate system and station tab
- set the new name, I thought a better name will result in more users. my proposal is "Intelligent Shipcomputer Extension"  

thats the current plan

**Comment by MRmP** [comment]
I'd like to get it fully up and running, I saw your message on the forum, I'll try that within the hour.
Its probably a better place to have this discussion, but the installer sounds important to make the tool easy to use,.
When I get it up and running, would it in theory work? (My typical usercase is: i fly between different stations and scan them, then ill do some traderuns based on the data) I'f not I would love to get that up and running

**Comment by Duke-Jones** [comment]
yes, it is working and it is quick 
and - although still in development - there are better analysing possibilities 

two hints: 
1. if you OCRing you can't add new (unkown) commodities for the moment (see my current todo)
2. but i added a "external tool interface" which can be used by EDMC 
You get market data and the current station from it (there's unfortunately no station information anymore in the logfiles ) and so the "visited" and "market data collected" events are working again.

I hope the EDMC interface will work again soon :-|

**Comment by Duke-Jones** [comment]
additional information:
if you have started the sql-version, I recommend to import the data from the conventional RN with the import function firstly
I did the import a few times and it worked - for me.
So I hope it will for you too

**Pull request merged**
