### PR TITLE
fix invalid cast from EDCommoditiesExt to int

### PR DESCRIPTION
**Pull request by WiredSharp**
replace the int cast by EDCommoditiesExt Id lookup.
Add a CurrentCommodity property in order to retrieve the currently selected commodity.

### CODE REVIEW

**Comment by Duke-Jones** [comment]
hi. i will check this. thx for helping

**Comment by Duke-Jones** [comment]
I guess there something went wrong on your changes.
A user in the german forum reported a crash in the 0.19 if he starts the 
view of the warnlevels. The v0.18 is running without problems - 
I can't reproduce the crash on my computer. 
Can you have a look on your changes, please ?

http://www.elitedangerous.de/forum/viewtopic.php?f=66&t=6404&start=100#p118647

**Comment by WiredSharp** [comment]
Hi, i Will check it quickly, i hope we will soon have unit tests for localisation issue as they may be hard to catch with regular validation

**Comment by WiredSharp** [comment]
Do You open any issue i should refer?

**Pull request merged**
