### PR TITLE
Commodities

### PR DESCRIPTION
**Pull request by WiredSharp**
Hi, here is some improvment you may be interested in:
- download missing data files
- auto-listen to EDDN at start option
- new Commodities model to store marketdata (synchronize station and commodities market)
- json parsing cleanup
- implausible market data with more details
- testing tab which allow to simulate fake OCR or fake EDDN message for test

### CODE REVIEW

**Comment by WiredSharp** [comment]
fixed plausibility check on EDDN message received

**Comment by Duke-Jones** [comment]
uh, looks like a lot of work. I will have a look asap and merge it.

thanks

**Comment by Duke-Jones** [comment]
You are very busy on this project I notice more an more
that I can't spend enough time to manage this project in future.
So I want to ask you to take over this project.

What do you think ?

**Comment by WiredSharp** [comment]
I had a week or holidays so i had plenty on time to work on, but i won't have so much time In the future, maybe we can share the ownership or the project and work at our own rate.

**Comment by Duke-Jones** [comment]
Yes, ok.
I didn't do this on github before (I'm completely new to git hub).
Do I add you as "Collaborator" or how can we do this ? I think it's
important that you can merge the project and maybe
also prepare  a new release on your own, ok ?

**Comment by WiredSharp** [comment]
Yes, that would be great, i'm also using this project to improve my skills with git and github, i'm very interested in an experience in online collaborative project and even international

**Comment by WiredSharp** [comment]
I do not know also how to manage project on github but feel free to experiment

**Comment by Duke-Jones** [comment]
Ok , I think I will add you as collaborator and then we'll see what's working or not.
Do you work on your own or with other guys ? I see different names on your
commits (zerrico, ebl, laenckel, ....) ?

I added a few small but important changes on my last commits. Please be sure
you get those in your changes before merging or even add a optimized solution.
(e. g. "the duplicate filter on OCRed data" or the "check for the existing path on auto-find ED path on first start).

The next days we should talk a little bit about "who's doing what" to prevent multiple work
on the same issues .. .  but one after the other.....

I will add you now to this project......

**Comment by WiredSharp** [comment]
no i am alone but several accounts on different computers.
i merged your last commit in my branch. i had already made the fix for path auto-finding, i still have to check what oyou have done for OCRed data.
Yes, it is important to know what each of us is working on, as you may have noticed, i am more oriented in backend and architecture.
I have a friend who is interested in working on UI to make it more sexy, he makes nice looking things.

**Comment by WiredSharp** [comment]
All right i saw your update for OCRed data, it is correctly integrated in my branch.

**Comment by Duke-Jones** [comment]
It's a simple/quick and dirty duplicate check-function in Form1.
There may be better solutions to optimize this and put this directly in the OCR-class
but at this moment it was near at hand to check the data (badly in a GUI object) 
on every addiditon from the OCR algorithm.
I think it's neccessary also to add a equivalent filter with a additional expiring time (e. g. 5 minutes)
to the EDDN send function. This is one thing I would to as next.

A problem in general is the speed of filtering stations at the moment. I already started a try to
filter stations by landingpad-size but it was to slow. So I decided to dismiss this filter
and wanted to think about it again in rest. 
(The optimum surely is a small sql database server but this is not a small change ;-) )

So badly I have to leave for today. Hope I find a little time for this project tomorrow.

cu, Duke

**Comment by WiredSharp** [comment]
the problem is that station filtering does not use a dictionary, i think it will be quite more responsive with my StarMap instead of Milkyway.

**Comment by Duke-Jones** [comment]
Ok, I very tensely. My goal was it to be quick enough even with about 1000 stations.

**Comment by WiredSharp** [comment]
i will try a sorteddictionary, which could be more efficient with few add/remove.As we add or remove few station during application runtime, only at start. And with index on name, research will be far more efficient.

**Comment by WiredSharp** [comment]
My friend think about a WPF GUi which may be more sexy than current one. i go on isolatiing business and gui logic as it is very intricated in main form. As soon as we could use my model, we could be able to manipulate data quickly and effectively. My applicationContext branch start using it in a mixed way in order to progressively migrate to the new model. I think my friend will create the new GUI in parallel, if he works fast enough, i won't have to adapt the current mainform.

**Comment by Duke-Jones** [comment]
Let your friend do this. 
I think over to publish a new version this evening.
Would this be ok ?  I will not test any of your changes !

**Comment by Duke-Jones** [comment]
Please, if you think you've something which is worth to merge it
so merge it by yourself and add a small summary of the changes
in the TODO.txt in the project directory. 

So I can quickly add your summary of changes into the "what has changed info"
for the current release without searching.

**Comment by Duke-Jones** [comment]
I've tried to compile the merged project but 
got 99 errors and 13 warnings. 

Please check...

**Comment by WiredSharp** [comment]
all right i check

**Comment by WiredSharp** [comment]
in which configuration? i don't have any error, do you have Nuget add-in installed?

**Comment by Duke-Jones** [comment]
the default "Debug DJ" configuration.
"Nuget add-in": no. is it necessary now?
......
Oops, I started VS again and I can compile now without problems.
Sorry, sure it was my mistake. Seems everything's ok.
No idea why it did'nt work before .

**Comment by WiredSharp** [comment]
good to hear it. i am having a look on Issue #44. I will push updated Todo also.

**Comment by Duke-Jones** [comment]
I released v0.21  - looks good.
Issue #44 should be gone with the duplicate filter or have you 
added anything else on this ?

**Comment by WiredSharp** [comment]
i still haven't found the cause of the disturbance. I do not know also if you want to release the tradedangerous data import functionalty?

**Pull request merged**
